import React from "react";
import { handler } from "../api";
import Link from "next/link";
import Head from "next/head";
import Layout from "../../components/Layout";

function Sections({ results, title }) {
  return (
    <Layout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>
        <ul>
          {results?.map((result) => {
            return (
              <>
                -{" "}
                <Link href={`sections/${result.section}`}>
                  <a>{result.display_name}</a>
                </Link>
                <br />
              </>
            );
          })}
        </ul>
      </main>
    </Layout>
  );
}

const API_KEY = "9hUvOqGGdnCBvGKg4EB3L7mGdBC8hKKJ";
export async function getStaticProps({ params }) {
  const URL = `https://api.nytimes.com/svc/news/v3/content/section-list.json?api-key=${API_KEY}`;
  // Pass post data to the page via props

  return {
    props: {
      results: await handler(URL),
      title: "Sections",
    },
  };
}

export default Sections;
